### ISSUE TITLE
프로젝트 기초 세팅

### ISSUE THREAD

**Issue by hemudi** [hemudi/fe-vm#1]
## Description
CRA를 이용한 리액트 프로젝트의 초기 설정을 한다.
또한 커밋 컨벤션, 이슈 템플릿 같은 프로젝트 룰에 대해서도 README에 간략히 정리한다.

## Tasks
- [x] CRA 설치 & 불필요한 파일과 코드 제거
- [x] favicon 변경
- [x] ESLint & Prettier 설정
- [x] 절대 경로 설정
- [x] README 1차 작성
- [x] Styled Components 설치
