### ISSUE TITLE
절대경로 재세팅

### ISSUE THREAD

**Issue by hemudi** [hemudi/fe-vm#12]
## Description
Story book 의 오류를 회피하기 위해 임시로 사용한 상대경로를 전부 전대경로로 수정한다.
또한 경로를 수정하는 김에 Styled components의 import 방식을 별칭을 사용하는 방식으로 통일한다.

## Tasks
- [x] Story Test Code 경로 수정
- [x] components jsx 파일 이름 index.jsx로 변경 
- [x] Styled components import 방식 통일
