### ISSUE TITLE
Mock Server & Mock Data 생성

### ISSUE THREAD

**Issue by hemudi** [hemudi/fe-vm#13]
## Description
Json Server 를 이용한 Mock Server 와 Mock Data 를 생성한다.
또한 Json Server 와의 통신을 위한 Fetch util 함수를 구현한다.

## Tasks
- [x] Json Server 설치
- [x] Json Server 환경 설정
- [x] Mock Data 생성
- [x] Axios 설치 & baseUrl 설정한 Instance 생성
