### ISSUE TITLE
Global Style & Theme 생성과 Atom Components 구현

### ISSUE THREAD

**Issue by hemudi** [hemudi/fe-vm#2]
## Description
Styled Components를 이용해 Global 스타일과 Theme를 구현한다.
Atomic Design 방식을 활용한 Button Atom 컴포넌트를 구현한다.

## Tasks
- [x] Atomic Components 디렉터리 구조 구현
- [x] Atom 구현
  - [x] Styled Components를 이용하여 Style 구현
  - [x] Story Book 활용하여 테스트 코드 작성

| Atom Type     | 구현 여부 |
|--------------|:-------:|
| Button            | ✅     |
| LogoImage    | ✅         |
| LogoTitle       | ✅         |
| Icon                | ✅         |
| Input               | ✅         |
| Label              | ✅         |
| ListItem         | ✅         |
