### ISSUE TITLE
1주차 금요일 PR 리뷰 반영

### ISSUE THREAD

**Issue by hemudi** [hemudi/fe-vm#6]
## Description
1주차 금요일 PR 리뷰를 반영한다.

## Tasks
- [x]  map key 변경
- [x] Props 괄호 제거 해보기
- [x] Flex 개선
- [x] children 방식 통일
- [x] display 이름 변경
