### ISSUE TITLE
페이지 전환 애니메이션 구현

### ISSUE THREAD

**Issue by hemudi** [hemudi/fe-vm#9]
## Description
React-trasition-group 을 활용하여 페이지 전환 애니메이션 구현

## Tasks
- [x] Router 구조 변경
  - [x] VMController 는 재렌더링 되지 않고 유지
  - [x] path 조건을 활용하여 Outlet 위치 제어
- [x] React-trasition-group 설치
- [ ] 페이지 전환 애니메이션 구현
